server:
  port: 8765
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
spring:
  datasource:
    url: ${POSTGRES_SERVER_ADDRESS:jdbc:postgresql://localhost:5432/product_security_db}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: API-GATEWAY
  cloud:
    gateway:

      routes:
        - id : ORDER-SERVICE
          uri : lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - TokenRelay=
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - TokenRelay=
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - TokenRelay=

  security:
    oauth2:
      client:
        registration:
            okta:
                client-id: 0oaf1kz9cpI7vpqtl5d7
                client-secret: KnWDwRBAzV-OQRRV0072XwNEfaotr_07Evpbs28yK3ul6vdD4Az9__xwd8d9VBxA
                scope: openid, profile, email, offline_access, internal
                redirect-uri: ${REDIRECT_URI:http://localhost:8765/login/oauth2/code/okta}
#                redirect-uri: ${REDIRECT_URI:http://gateway.localtest.me/login/oauth2/code/okta}
                authorization-grant-type: authorization_code
        provider:
          okta:
            issuer-uri: https://dev-43724657.okta.com/oauth2/default
      resourceserver:
        jwt:
          issuer-uri: https://dev-43724657.okta.com/oauth2/default
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml


logging:
  level:
    org:
      springframework:
        security: DEBUG
